apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-intensivo
  selector:
    matchLabels:
      app: go-intensivo
    metadata:
      labels:
        app: go-intensivo
      containers:
      - name: go-intensivo
        image: marcosnasp/go-intensivo:1.0
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 9090